% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2.54cm]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Assignment 3: Data Exploration},
  pdfauthor={Lexi Nelson},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Assignment 3: Data Exploration}
\author{Lexi Nelson}
\date{Spring 2026}

\begin{document}
\maketitle

\subsection{OVERVIEW}\label{overview}

This exercise accompanies the lessons in Environmental Data Analytics on
Data Exploration.

\subsection{Directions}\label{directions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Rename this file
  \texttt{\textless{}FirstLast\textgreater{}\_A03\_DataExploration.Rmd}
  (replacing \texttt{\textless{}FirstLast\textgreater{}} with your first
  and last name).
\item
  Change ``Student Name'' on line 3 (above) with your name.
\item
  Work through the steps, \textbf{creating code and output} that fulfill
  each instruction.
\item
  {[}NEW{]} Assign a useful \textbf{name to each code chunk} and include
  ample \textbf{comments} with your code.
\item
  Be sure to \textbf{answer the questions} in this assignment document.
\item
  When you have completed the assignment, \textbf{Knit} the text and
  code into a single PDF file.
\item
  After Knitting, submit the completed exercise (PDF file) to Canvas.
\item
  Initial here to acknowledge that you did not use AI in completing this
  assignment, except where expressly allowed: AN
\end{enumerate}

\textbf{TIP}: If your code extends past the page when knit, tidy your
code by manually inserting line breaks in your code chunks.

\textbf{TIP}: If your code fails to knit, check: * That no
\texttt{install.packages()} or \texttt{View()} commands exist in your
code. * That you are not displaying the entire contents of a large
dataframe in your code.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Set up your R session}\label{set-up-your-r-session}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Load necessary packages (tidyverse, here), check your current working
  directory and import two datasets: the ECOTOX neonicotinoid dataset
  (ECOTOX\_Neonicotinoids\_Insects\_raw.csv) and the Niwot Ridge NEON
  dataset for litter and woody debris
  (NEON\_NIWO\_Litter\_massdata\_2018-08\_raw.csv). Name these datasets
  ``Neonics'' and ``Litter'', respectively.
\end{enumerate}

\textbf{Be sure to}: * Use the \texttt{here()} package in specifying the
paths to your datasets * Include the appropriate subcommand to read in
character based columns as factors

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#setup R session and load necessary packages}
\FunctionTok{library}\NormalTok{(tidyverse) }\CommentTok{\#load tidyverse}
\FunctionTok{library}\NormalTok{(here) }\CommentTok{\#load here as we worked with in Lab 3}

\FunctionTok{here}\NormalTok{() }\CommentTok{\#confirm where here command will point}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/home/guest/ENV872/EDE_Spring2026/Assignments"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{getwd}\NormalTok{() }\CommentTok{\#check working directory}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/home/guest/ENV872/EDE_Spring2026/Assignments"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#I coped the two data files from the EDE\_Spring2026 raw data folder into a Data folder under my Assignments folder. I did this so that R could access the data in my working directory using "here".}

\CommentTok{\#read in Neonicotinoids data set}
\NormalTok{Neonics }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}
  \AttributeTok{file =} \FunctionTok{here}\NormalTok{(}\StringTok{\textquotesingle{}Data\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}ECOTOX\_Neonicotinoids\_Insects\_raw.csv\textquotesingle{}}\NormalTok{),}
  \AttributeTok{stringsAsFactors =}\NormalTok{ T }
\NormalTok{)}
\CommentTok{\#stringsasFactors is the command to read in character based columns as factors}

\CommentTok{\#read in NEON data set}
\NormalTok{Litter }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}
  \AttributeTok{file =} \FunctionTok{here}\NormalTok{(}\StringTok{\textquotesingle{}Data\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}NEON\_NIWO\_Litter\_massdata\_2018{-}08\_raw.csv\textquotesingle{}}\NormalTok{),}
  \AttributeTok{stringsAsFactors =}\NormalTok{ T}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}

## Learn about your system

2.  The neonicotinoid dataset was collected from the Environmental Protection Agency's ECOTOX Knowledgebase, a database for ecotoxicology research. Neonicotinoids are a class of insecticides used widely in agriculture. The dataset that has been pulled includes all studies published on insects. Why might we be interested in the ecotoxicology of neonicotinoids on insects? Feel free to do a brief internet search if you feel you need more background information. (AI is allowed here, but put answers in your own words.)

> Answer: Neonicotinioids are designed to protect insects by killing plants. We are interested in the ecotoxicology of neonicotinoids on insects because they are directly impacted. We would like to understand the mechanisms by which the toxins act on insects. Additionally, insects underpin the entire food web, so there could be cascading effects of the neonicotinoid use. 


3.  The Niwot Ridge litter and woody debris dataset was collected from the National Ecological Observatory Network, which collectively includes 81 aquatic and terrestrial sites across 20 ecoclimatic domains. 32 of these sites sample forest litter and woody debris, and we will focus on the Niwot Ridge long-term ecological research (LTER) station in Colorado. Why might we be interested in studying litter and woody debris that falls to the ground in forests? Feel free to do a brief internet search if you feel you need more background information. (AI is allowed here, but put answers in your own words.)

> Answer:Litter and woody debris contain nutrients such as CO2 and others. These molecules can decompose and release nutrients back to the atmosphere and soil. They also serve as a habitat for some creatures and prevent erosion. Studying the quantity of this debris and its component nutrients may help scientists understand the health of the ecosystem and speed of forest carbon cycles and more broadly, climate change.


4.  How is litter and woody debris sampled as part of the NEON network? Read the NEON_Litterfall_UserGuide.pdf document to learn more. List three pieces of salient information about the sampling methods here:

> Answer: 
 1.The sampling guide divides the litter into 8 different functional groups (leaves, needles, twigs/branches, woody materials, seeds, flowers and other non-woody reproductive structures, other, and mixed material).The mass of each functional group is recorded with an accuracy of 0.01 grams.
 2.Sampling occurs at NEON sites that contain woody vegetation over 2 meters tall.
 3. Ground traps are sampled once per year.


## Obtain basic summaries of your data (Neonics)

5.  What are the dimensions of the dataset?


``` r
#find the dimensions of the dataset
dim(Neonics) 
\end{verbatim}

\begin{verbatim}
## [1] 4623   30
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#returns number of rows and columns: 4623 rows by 30 columns}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Using the \texttt{summary} function on the ``Effect'' column,
  determine the most common effects that are studied. {[}Tip: The
  \texttt{sort()} command is useful for listing the values in order of
  magnitude\ldots{]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#view a summary of the effect column to understand the most common effects that are studied}
\NormalTok{effects\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(Neonics}\SpecialCharTok{$}\NormalTok{Effect)}
\CommentTok{\#sort from largest to smallest to display most common effects at the top}
\NormalTok{sorted\_effects\_summary }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(effects\_summary, }\AttributeTok{decreasing=}\ConstantTok{TRUE}\NormalTok{) }
\FunctionTok{print}\NormalTok{(sorted\_effects\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Population        Mortality         Behavior Feeding behavior 
##             1803             1493              360              255 
##     Reproduction      Development        Avoidance         Genetics 
##              197              136              102               82 
##        Enzyme(s)           Growth       Morphology    Immunological 
##               62               38               22               16 
##     Accumulation     Intoxication     Biochemistry          Cell(s) 
##               12               12               11                9 
##       Physiology        Histology       Hormone(s) 
##                7                5                1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#three most common effects studied are population, mortality, and. behavior (in order)}
\end{Highlighting}
\end{Shaded}

► Question: Which two effects stand out as the most studied? Can you
guess why these effects might specifically be of interest?
\textgreater{} Answer: Population and mortality were most studied (1803
and 1493 entries, respectively). I am guessing these are effects are of
interest because neonicotinoids are intended to kill the insects, so
these two effects can give direct insight into their effectiveness in
that regard. Also, you cannot measure other behavior of the insects if
they are not alive, so that may explain why the other behaviors are less
frequently recorded.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{6}
\tightlist
\item
  Using the \texttt{summary} function, determine the six most commonly
  studied species in the dataset (common name).{[}TIP: Explore the help
  on the \texttt{summary()} function, in particular the \texttt{maxsum}
  argument\ldots{]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#determine 6 most commonly studied species}
\CommentTok{\#get a summary of the Species.Common.Name column}
\CommentTok{\#use the maxsum argument, which Help says is an integer indicating how many levels should be shown for factors}
\NormalTok{species\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(Neonics}\SpecialCharTok{$}\NormalTok{Species.Common.Name, }\AttributeTok{maxsum=}\DecValTok{6}\NormalTok{)}
\CommentTok{\#sort from largest to smallest to display most common species at the top}
\NormalTok{sorted\_species\_summary }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(species\_summary, }\AttributeTok{decreasing=}\ConstantTok{TRUE}\NormalTok{) }
\FunctionTok{print}\NormalTok{(sorted\_species\_summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               (Other)             Honey Bee        Parasitic Wasp 
##                  3196                   667                   285 
## Buff Tailed Bumblebee   Carniolan Honey Bee            Bumble Bee 
##                   183                   152                   140
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Other is the most common result at 3196 observations, followed by honey bee 667, parasitic wasp 285, tailed bumblebee 183, carnolian honey bee 152, bumble bee 140}
\end{Highlighting}
\end{Shaded}

► Question: What do these species have in common? Why might they be of
interest over other insects? \textgreater{} Answer: Almost all of these
species are types of bumble bees. They might be of interest over other
insects since they are pollinators.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{7}
\tightlist
\item
  The \texttt{Conc.1..Author} column, which lists the concentration of
  the neonicitoid dose, should include numeric values. What is the class
  of \texttt{Conc.1..Author.} column in the dataset, and why is it not
  numeric? {[}Tip: Viewing the dataframe may be helpful\ldots{]}
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#check the class of the Conc.1..Author column}
\FunctionTok{class}\NormalTok{(Neonics}\SpecialCharTok{$}\NormalTok{Conc.}\DecValTok{1}\NormalTok{..Author)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#running the above command tells you it\textquotesingle{}s a factor}
\end{Highlighting}
\end{Shaded}

\begin{quote}
Answer:When looking at the data I can see there are some ``/'' in the
Conc.1..Author column along with the numbers, therefore R processed it
as factor data and not numeric.
\end{quote}

\subsection{Explore your data graphically
(Neonics)}\label{explore-your-data-graphically-neonics}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{8}
\tightlist
\item
  Using \texttt{geom\_freqpoly}, generate a plot of the number of
  studies conducted by publication year.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#generate a plot of studies per year with geom\_freqpoly}
\NormalTok{studies\_by\_yr }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(Neonics) }\SpecialCharTok{+} \FunctionTok{geom\_freqpoly}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Publication.Year))}
\FunctionTok{plot}\NormalTok{(studies\_by\_yr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-6-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{9}
\tightlist
\item
  Reproduce the same graph but now add a color aesthetic so that
  different Test.Location are displayed as different colors.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#reproduce the plot with a color aesthetic}
\NormalTok{studies\_by\_yr\_colored }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(Neonics) }\SpecialCharTok{+} \FunctionTok{geom\_freqpoly}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Publication.Year, }\AttributeTok{color =}\NormalTok{ Test.Location))}
\CommentTok{\#add color argument to geom\_freqpoly function to add the color aesthetic}
\FunctionTok{plot}\NormalTok{(studies\_by\_yr\_colored)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-7-1.pdf}

►Interpret this graph. What are the most common test locations, and do
they differ over time? \textgreater{} Answer:The most common test
location is the lab for a short time in the early 1990s and then it is
eclipsed by field natural until around 2000 when lab again becomes more
popular until around 2008. From around 2008-2010 field natural is the
most common test location. Then from 2010-2015 studies with lab test
location skyrocket and it is far more common than any other location.
From 2015-2020 lab studies dramatically decrease and are briedfly
eclipsed by field natural studies. Overall, field natural and lab test
locations are far more common than field artificial and field
undererminable, and switch off which of the two of them is the most
common over the 40 year period.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{10}
\tightlist
\item
  Create a bar graph of Endpoint counts.
\end{enumerate}

{[}\textbf{TIP}: Add
\texttt{theme(axis.text.x\ =\ element\_text(angle\ =\ 90,\ vjust\ =\ 0.5,\ hjust=1))}
to the end of your plot command to rotate and align the X-axis
labels\ldots{]}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create bar graph of Endpoint counts}
\NormalTok{endpoint\_counts }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Neonics, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Endpoint)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust=}\DecValTok{1}\NormalTok{))}
\NormalTok{endpoint\_counts}
\end{Highlighting}
\end{Shaded}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-8-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#theme argument added to end of plot command to rotate and align X{-}axis labels}
\end{Highlighting}
\end{Shaded}

► What are the two most common end points, and how are they defined?
Consult the ECOTOX\_CodeAppendix (p.721) for more information.
\textgreater{} Answer:The two most common end points are NOEL and LOEL.
LOEL means lowest-observable-effect-level, the lowest dose producing
results that were significantly different from controls.NOEL means
no-observable-effect-level, the highest dose producing effects not
significantly different from control responses.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{Explore your data (Litter)}\label{explore-your-data-litter}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{11}
\tightlist
\item
  Determine the class of \texttt{collectDate}. Is it a date? If not,
  change to a date and confirm the new class of the variable. Using the
  \texttt{unique} function, determine which dates litter was sampled in
  August 2018.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#check the class of the collectDate column}
\FunctionTok{class}\NormalTok{(Litter}\SpecialCharTok{$}\NormalTok{collectDate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "factor"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#returns factor}
\CommentTok{\#use Lubridate to work with dates since it\textquotesingle{}s easier}
\FunctionTok{library}\NormalTok{(lubridate)}
\NormalTok{Litter}\SpecialCharTok{$}\NormalTok{collectDate }\OtherTok{\textless{}{-}} \FunctionTok{ymd}\NormalTok{(Litter}\SpecialCharTok{$}\NormalTok{collectDate) }\CommentTok{\#put into Date class}
\FunctionTok{class}\NormalTok{(Litter}\SpecialCharTok{$}\NormalTok{collectDate) }\CommentTok{\#confirms it is now in date format }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Date"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#use unique to list the unique dates in the column}
\FunctionTok{unique}\NormalTok{(Litter}\SpecialCharTok{$}\NormalTok{collectDate)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "2018-08-02" "2018-08-30"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#returns 2018{-}08{-}02 and 2018{-}08{-}30 so we know Litter was sampled on those dates}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{12}
\tightlist
\item
  Using the \texttt{unique} function, list the different
  \texttt{plotIDs} sampled at Niwot Ridge.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create a new object to store unique plot IDs}
\FunctionTok{unique}\NormalTok{(Litter}\SpecialCharTok{$}\NormalTok{plotID)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] NIWO_061 NIWO_064 NIWO_067 NIWO_040 NIWO_041 NIWO_063 NIWO_047 NIWO_051
##  [9] NIWO_058 NIWO_046 NIWO_062 NIWO_057
## 12 Levels: NIWO_040 NIWO_041 NIWO_046 NIWO_047 NIWO_051 NIWO_057 ... NIWO_067
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#returns 12 different unique IDs: NIWO\_061 NIWO\_064 NIWO\_067 NIWO\_040 NIWO\_041 NIWO\_063 NIWO\_047 NIWO\_051 NIWO\_058 NIWO\_046 NIWO\_062 NIWO\_057}
\end{Highlighting}
\end{Shaded}

► How is the information obtained from \texttt{unique} different from
that obtained from \texttt{summary}? \textgreater{} Answer: The Summary
function when applied to a column will give a count of the number of
observations of each type. Whereas, the unique function will only return
each unique observation, and will not count how many times it appears in
the dataset.They both provide all unique observations but the Summary
function goes beyond the unique function by also providing the count.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{13}
\tightlist
\item
  Create a bar graph of \texttt{functionalGroup} counts. This shows you
  what type of litter is collected at the Niwot Ridge sites. Notice that
  litter types are fairly equally distributed across the Niwot Ridge
  sites.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#create bar graph using ggplot and x is functional group column}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Litter, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ functionalGroup)) }\SpecialCharTok{+} \FunctionTok{geom\_bar}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-11-1.pdf}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{14}
\tightlist
\item
  Using \texttt{geom\_boxplot} and \texttt{geom\_violin}, create a
  boxplot and a violin plot of \texttt{dryMass} by
  \texttt{functionalGroup}.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#again use ggplot with x=functional group column but add the two different plot types}
\CommentTok{\#I am not clear if these are supposed to be on the same plot so here I am assuming they are}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Litter, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ functionalGroup, }\AttributeTok{y =}\NormalTok{ dryMass)) }\SpecialCharTok{+} \FunctionTok{geom\_violin}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-12-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#violin plot only {-} this seems less useful}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Litter, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ functionalGroup, }\AttributeTok{y =}\NormalTok{ dryMass)) }\SpecialCharTok{+} \FunctionTok{geom\_violin}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-12-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#box plot only. I had to remove some NA values that were preventing the plot from displaying}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ Litter, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ functionalGroup, }\AttributeTok{y =}\NormalTok{ dryMass)) }\SpecialCharTok{+} \FunctionTok{geom\_boxplot}\NormalTok{(}\AttributeTok{na.rm=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{LexiNelson_A03_DataExploration_files/figure-latex/unnamed-chunk-12-3.pdf}

► Why is the boxplot a more effective visualization option than the
violin plot in this case?

\begin{quote}
Answer:The boxplots are more effective here due to the disparity in
number of observations per group. With some of the smaller groups, the
shapes created by the violin plot become hard to read and distinguish
from one another. The box plots show more in general, so they are more
informative, aesthetically pleasing, and allow us to see the spread,
median, IQR, and outliers more easily.
\end{quote}

► What type(s) of litter tend to have the highest biomass at these
sites? \textgreater{} Answer:Needles have a much higher median biomass
than any other type of litter. Mixed is the second highest litter type
in terms of biomass, while all other litter types have a low biomass.

\end{document}
